package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"

	"realm.pub/tavern/internal/builder/builderpb"
	"realm.pub/tavern/internal/graphql/generated"
)

// Params is the resolver for the params field.
func (r *buildTaskTomeConfigResolver) Params(ctx context.Context, obj *builderpb.BuildTaskTomeConfig) (string, error) {
	b, err := json.Marshal(obj.Params)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// BuildTaskTomeConfig returns generated.BuildTaskTomeConfigResolver implementation.
func (r *Resolver) BuildTaskTomeConfig() generated.BuildTaskTomeConfigResolver {
	return &buildTaskTomeConfigResolver{r}
}

type buildTaskTomeConfigResolver struct{ *Resolver }
