package shell

import (
	"net/http"

	"github.com/gorilla/websocket"
	"realm.pub/tavern/internal/ent"
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin:     func(r *http.Request) bool { return true },
}

////
// The below messages define an API contract between the browser and the server.
// Server to agent communication is instead defined by ent schemas and protocol buffers.
////

// WebsocketMessageKind describes the kind of websocket message being sent/received.
type WebsocketMessageKind string

// WebsocketMessageKindInput represents a shell input message.
// WebsocketMessageKindOutput represents a shell output message.
// WebsocketMessageKindTaskError represents a shell error message.
// WebsocketMessageKindError represents an error for the shell, not necessarily associated with any task.
// WebsocketMessageKindControlFlow represents a control plane message for the websocket, such as a keep-alive or close message.
const (
	WebsocketMessageKindInput       = "INPUT"
	WebsocketMessageKindOutput      = "OUTPUT"
	WebsocketMessageKindTaskError   = "TASK_ERROR"
	WebsocketMessageKindError       = "ERROR"
	WebsocketMessageKindControlFlow = "CONTROL_FLOW"
)

// WebsocketControlFlowSignal represents different kinds of control messages that can be sent.
type WebsocketControlFlowSignal string

// WebsocketControlFlowSignalClosed indicates that the connection is closed.
const (
	WebsocketControlFlowSignalClosed = "CLOSED"
)

// A WebsocketInputMessage is used to deliver input to a shell running on an agent.
// Kind should always be set to WebsocketMessageKindInput for this message type.
// Input represents an input string to be evaluated by a shell running on an agent.
// Note that ShellTaskID and CreatorID are not defined here, because they are determined by the server.
//   - CreatorID is determined from the authenticated user with the active websocket connection.
//   - ShellTaskID will be the ID of the ShellTask that is created as a result of this message.
type WebsocketInputMessage struct {
	Kind  WebsocketMessageKind `json:"kind"`
	Input string               `json:"input"`
}

// A WebsocketInputMessage is used to deliver output from a shell running on an agent.
// Kind should always be set to WebsocketMessageKindOutput for this message type.
// Output represents the output generated by the ShellTask from running on an agent.
type WebsocketOutputMessage struct {
	Kind        WebsocketMessageKind `json:"kind"`
	Output      string               `json:"output"`
	ShellTaskID int                  `json:"shell_task_id"`
	CreatorID   int                  `json:"owner"`
}

// NewWebsocketOutputMessage creates a new output message to be sent to the browser on the websocket.
func NewWebsocketOutputMessage(task *ent.ShellTask) *WebsocketOutputMessage {
	var creatorID int
	if task.Edges.Creator != nil {
		creatorID = task.Edges.Creator.ID
	}

	return &WebsocketOutputMessage{
		Kind:        WebsocketMessageKindOutput,
		Output:      task.Output,
		ShellTaskID: task.ID,
		CreatorID:   creatorID,
	}
}

// A WebsocketTaskErrorMessage is used to deliver errors from a shell running on an agent.
// Kind should always be set to WebsocketMessageKindTaskError for this message type.
// Error holds the error message from the agent shell.
// ShellTaskID represents the id of the ShellTask that the error corresponds to.
// CreatorID represents the owner of the ShellTask that the error corresponds to.
type WebsocketTaskErrorMessage struct {
	Kind        WebsocketMessageKind `json:"kind"`
	Error       string               `json:"error"`
	ShellTaskID int                  `json:"shell_task_id"`
	CreatorID   int                  `json:"owner"`
}

// NewWebsocketTaskErrorMessage creates a new error message to be sent to the browser on the websocket.
func NewWebsocketTaskErrorMessage(task *ent.ShellTask) *WebsocketTaskErrorMessage {
	var creatorID int
	if task.Edges.Creator != nil {
		creatorID = task.Edges.Creator.ID
	}
	return &WebsocketTaskErrorMessage{
		Kind:        WebsocketMessageKindTaskError,
		Error:       task.Error,
		ShellTaskID: task.ID,
		CreatorID:   creatorID,
	}
}

// A WebsocketTaskErrorMessage is used to deliver errors from a shell running on an agent.
// Kind should always be set to WebsocketMessageKindError for this message type.
// Error holds the error message
// ShellTaskID represents the id of the ShellTask that the error corresponds to.
// CreatorID represents the owner of the ShellTask that the error corresponds to.
type WebsocketErrorMessage struct {
	Kind  WebsocketMessageKind `json:"kind"`
	Error string               `json:"error"`
}

// NewWebsocketErrorMessage creates a new error message to be sent to the browser on the websocket.
func NewWebsocketErrorMessage(err error) *WebsocketErrorMessage {
	return &WebsocketErrorMessage{
		Kind:  WebsocketMessageKindError,
		Error: err.Error(),
	}
}

// WebsocketControlFlowMessage represents control plane messages to control the operation of the websocket, such as a closed message.
type WebsocketControlFlowMessage struct {
	Kind   WebsocketMessageKind       `json:"kind"`
	Signal WebsocketControlFlowSignal `json:"signal"`
}

// NewWebsocketClosedMessage indicates that the connection has been closed.
func NewWebsocketClosedMessage() *WebsocketControlFlowMessage {
	return &WebsocketControlFlowMessage{
		Kind:   WebsocketMessageKindControlFlow,
		Signal: WebsocketControlFlowSignalClosed,
	}
}
