codecov:
  notify:
    wait_for_ci: yes
    after_n_builds: 9  # Updated: 3 implants (ubuntu, macos, windows) + 1 tavern + 1 ui-tests = 5, being conservative with 9

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  tavern:
    paths:
      - tavern/
    carryforward: false
  implants:
    paths:
      - implants/
    carryforward: false
  ui-tests:
    paths:
      - tavern/internal/www/src/
    carryforward: false

ignore:
  - "**/*.pb.go" # Ignore Generated Protobufs
  - "**/*.generated.go" # Ignore Generated Code
  - tavern/internal/graphql/models/gqlgen_models.go
  - implants/lib/pb/src/generated/*.rs # Ignore Generated Protobufs
  - tavern/internal/ent/ # Ignore Ent Generated Code
  - tavern/internal/c2/c2test # Ignore test util package
  - tavern/internal/www/node_modules/ # Ignore Node modules
  - tavern/internal/www/build/ # Ignore build artifacts
  - tavern/internal/www/src/components # Ignore components for now
  - tavern/internal/www/src/pages
  - tavern/internal/www/utils
