// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"realm.pub/tavern/internal/ent/beacon"
	"realm.pub/tavern/internal/ent/file"
	"realm.pub/tavern/internal/ent/host"
	"realm.pub/tavern/internal/ent/hostcredential"
	"realm.pub/tavern/internal/ent/hostfile"
	"realm.pub/tavern/internal/ent/hostprocess"
	"realm.pub/tavern/internal/ent/quest"
	"realm.pub/tavern/internal/ent/repository"
	"realm.pub/tavern/internal/ent/schema"
	"realm.pub/tavern/internal/ent/shell"
	"realm.pub/tavern/internal/ent/tag"
	"realm.pub/tavern/internal/ent/task"
	"realm.pub/tavern/internal/ent/tome"
	"realm.pub/tavern/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	beaconMixin := schema.Beacon{}.Mixin()
	beaconMixinFields0 := beaconMixin[0].Fields()
	_ = beaconMixinFields0
	beaconFields := schema.Beacon{}.Fields()
	_ = beaconFields
	// beaconDescCreatedAt is the schema descriptor for created_at field.
	beaconDescCreatedAt := beaconMixinFields0[0].Descriptor()
	// beacon.DefaultCreatedAt holds the default value on creation for the created_at field.
	beacon.DefaultCreatedAt = beaconDescCreatedAt.Default.(func() time.Time)
	// beaconDescLastModifiedAt is the schema descriptor for last_modified_at field.
	beaconDescLastModifiedAt := beaconMixinFields0[1].Descriptor()
	// beacon.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	beacon.DefaultLastModifiedAt = beaconDescLastModifiedAt.Default.(func() time.Time)
	// beacon.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	beacon.UpdateDefaultLastModifiedAt = beaconDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// beaconDescName is the schema descriptor for name field.
	beaconDescName := beaconFields[0].Descriptor()
	// beacon.DefaultName holds the default value on creation for the name field.
	beacon.DefaultName = beaconDescName.Default.(func() string)
	// beacon.NameValidator is a validator for the "name" field. It is called by the builders before save.
	beacon.NameValidator = beaconDescName.Validators[0].(func(string) error)
	// beaconDescPrincipal is the schema descriptor for principal field.
	beaconDescPrincipal := beaconFields[1].Descriptor()
	// beacon.PrincipalValidator is a validator for the "principal" field. It is called by the builders before save.
	beacon.PrincipalValidator = beaconDescPrincipal.Validators[0].(func(string) error)
	// beaconDescIdentifier is the schema descriptor for identifier field.
	beaconDescIdentifier := beaconFields[2].Descriptor()
	// beacon.DefaultIdentifier holds the default value on creation for the identifier field.
	beacon.DefaultIdentifier = beaconDescIdentifier.Default.(func() string)
	// beacon.IdentifierValidator is a validator for the "identifier" field. It is called by the builders before save.
	beacon.IdentifierValidator = beaconDescIdentifier.Validators[0].(func(string) error)
	// beaconDescAgentIdentifier is the schema descriptor for agent_identifier field.
	beaconDescAgentIdentifier := beaconFields[3].Descriptor()
	// beacon.AgentIdentifierValidator is a validator for the "agent_identifier" field. It is called by the builders before save.
	beacon.AgentIdentifierValidator = beaconDescAgentIdentifier.Validators[0].(func(string) error)
	fileMixin := schema.File{}.Mixin()
	fileHooks := schema.File{}.Hooks()
	file.Hooks[0] = fileHooks[0]
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileMixinFields0[0].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescLastModifiedAt is the schema descriptor for last_modified_at field.
	fileDescLastModifiedAt := fileMixinFields0[1].Descriptor()
	// file.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	file.DefaultLastModifiedAt = fileDescLastModifiedAt.Default.(func() time.Time)
	// file.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	file.UpdateDefaultLastModifiedAt = fileDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// fileDescName is the schema descriptor for name field.
	fileDescName := fileFields[0].Descriptor()
	// file.NameValidator is a validator for the "name" field. It is called by the builders before save.
	file.NameValidator = fileDescName.Validators[0].(func(string) error)
	// fileDescSize is the schema descriptor for size field.
	fileDescSize := fileFields[1].Descriptor()
	// file.DefaultSize holds the default value on creation for the size field.
	file.DefaultSize = fileDescSize.Default.(int)
	// file.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	file.SizeValidator = fileDescSize.Validators[0].(func(int) error)
	// fileDescHash is the schema descriptor for hash field.
	fileDescHash := fileFields[2].Descriptor()
	// file.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	file.HashValidator = fileDescHash.Validators[0].(func(string) error)
	hostMixin := schema.Host{}.Mixin()
	hostMixinFields0 := hostMixin[0].Fields()
	_ = hostMixinFields0
	hostFields := schema.Host{}.Fields()
	_ = hostFields
	// hostDescCreatedAt is the schema descriptor for created_at field.
	hostDescCreatedAt := hostMixinFields0[0].Descriptor()
	// host.DefaultCreatedAt holds the default value on creation for the created_at field.
	host.DefaultCreatedAt = hostDescCreatedAt.Default.(func() time.Time)
	// hostDescLastModifiedAt is the schema descriptor for last_modified_at field.
	hostDescLastModifiedAt := hostMixinFields0[1].Descriptor()
	// host.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	host.DefaultLastModifiedAt = hostDescLastModifiedAt.Default.(func() time.Time)
	// host.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	host.UpdateDefaultLastModifiedAt = hostDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// hostDescIdentifier is the schema descriptor for identifier field.
	hostDescIdentifier := hostFields[0].Descriptor()
	// host.IdentifierValidator is a validator for the "identifier" field. It is called by the builders before save.
	host.IdentifierValidator = hostDescIdentifier.Validators[0].(func(string) error)
	// hostDescName is the schema descriptor for name field.
	hostDescName := hostFields[1].Descriptor()
	// host.NameValidator is a validator for the "name" field. It is called by the builders before save.
	host.NameValidator = hostDescName.Validators[0].(func(string) error)
	hostcredentialMixin := schema.HostCredential{}.Mixin()
	hostcredentialMixinFields0 := hostcredentialMixin[0].Fields()
	_ = hostcredentialMixinFields0
	hostcredentialFields := schema.HostCredential{}.Fields()
	_ = hostcredentialFields
	// hostcredentialDescCreatedAt is the schema descriptor for created_at field.
	hostcredentialDescCreatedAt := hostcredentialMixinFields0[0].Descriptor()
	// hostcredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	hostcredential.DefaultCreatedAt = hostcredentialDescCreatedAt.Default.(func() time.Time)
	// hostcredentialDescLastModifiedAt is the schema descriptor for last_modified_at field.
	hostcredentialDescLastModifiedAt := hostcredentialMixinFields0[1].Descriptor()
	// hostcredential.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	hostcredential.DefaultLastModifiedAt = hostcredentialDescLastModifiedAt.Default.(func() time.Time)
	// hostcredential.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	hostcredential.UpdateDefaultLastModifiedAt = hostcredentialDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// hostcredentialDescPrincipal is the schema descriptor for principal field.
	hostcredentialDescPrincipal := hostcredentialFields[0].Descriptor()
	// hostcredential.PrincipalValidator is a validator for the "principal" field. It is called by the builders before save.
	hostcredential.PrincipalValidator = hostcredentialDescPrincipal.Validators[0].(func(string) error)
	// hostcredentialDescSecret is the schema descriptor for secret field.
	hostcredentialDescSecret := hostcredentialFields[1].Descriptor()
	// hostcredential.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	hostcredential.SecretValidator = hostcredentialDescSecret.Validators[0].(func(string) error)
	hostfileMixin := schema.HostFile{}.Mixin()
	hostfileHooks := schema.HostFile{}.Hooks()
	hostfile.Hooks[0] = hostfileHooks[0]
	hostfileMixinFields0 := hostfileMixin[0].Fields()
	_ = hostfileMixinFields0
	hostfileFields := schema.HostFile{}.Fields()
	_ = hostfileFields
	// hostfileDescCreatedAt is the schema descriptor for created_at field.
	hostfileDescCreatedAt := hostfileMixinFields0[0].Descriptor()
	// hostfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	hostfile.DefaultCreatedAt = hostfileDescCreatedAt.Default.(func() time.Time)
	// hostfileDescLastModifiedAt is the schema descriptor for last_modified_at field.
	hostfileDescLastModifiedAt := hostfileMixinFields0[1].Descriptor()
	// hostfile.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	hostfile.DefaultLastModifiedAt = hostfileDescLastModifiedAt.Default.(func() time.Time)
	// hostfile.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	hostfile.UpdateDefaultLastModifiedAt = hostfileDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// hostfileDescPath is the schema descriptor for path field.
	hostfileDescPath := hostfileFields[0].Descriptor()
	// hostfile.PathValidator is a validator for the "path" field. It is called by the builders before save.
	hostfile.PathValidator = hostfileDescPath.Validators[0].(func(string) error)
	// hostfileDescSize is the schema descriptor for size field.
	hostfileDescSize := hostfileFields[4].Descriptor()
	// hostfile.DefaultSize holds the default value on creation for the size field.
	hostfile.DefaultSize = hostfileDescSize.Default.(uint64)
	// hostfile.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	hostfile.SizeValidator = hostfileDescSize.Validators[0].(func(uint64) error)
	// hostfileDescHash is the schema descriptor for hash field.
	hostfileDescHash := hostfileFields[5].Descriptor()
	// hostfile.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	hostfile.HashValidator = hostfileDescHash.Validators[0].(func(string) error)
	hostprocessMixin := schema.HostProcess{}.Mixin()
	hostprocessMixinFields0 := hostprocessMixin[0].Fields()
	_ = hostprocessMixinFields0
	hostprocessFields := schema.HostProcess{}.Fields()
	_ = hostprocessFields
	// hostprocessDescCreatedAt is the schema descriptor for created_at field.
	hostprocessDescCreatedAt := hostprocessMixinFields0[0].Descriptor()
	// hostprocess.DefaultCreatedAt holds the default value on creation for the created_at field.
	hostprocess.DefaultCreatedAt = hostprocessDescCreatedAt.Default.(func() time.Time)
	// hostprocessDescLastModifiedAt is the schema descriptor for last_modified_at field.
	hostprocessDescLastModifiedAt := hostprocessMixinFields0[1].Descriptor()
	// hostprocess.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	hostprocess.DefaultLastModifiedAt = hostprocessDescLastModifiedAt.Default.(func() time.Time)
	// hostprocess.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	hostprocess.UpdateDefaultLastModifiedAt = hostprocessDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// hostprocessDescPrincipal is the schema descriptor for principal field.
	hostprocessDescPrincipal := hostprocessFields[3].Descriptor()
	// hostprocess.PrincipalValidator is a validator for the "principal" field. It is called by the builders before save.
	hostprocess.PrincipalValidator = hostprocessDescPrincipal.Validators[0].(func(string) error)
	questMixin := schema.Quest{}.Mixin()
	questMixinFields0 := questMixin[0].Fields()
	_ = questMixinFields0
	questFields := schema.Quest{}.Fields()
	_ = questFields
	// questDescCreatedAt is the schema descriptor for created_at field.
	questDescCreatedAt := questMixinFields0[0].Descriptor()
	// quest.DefaultCreatedAt holds the default value on creation for the created_at field.
	quest.DefaultCreatedAt = questDescCreatedAt.Default.(func() time.Time)
	// questDescLastModifiedAt is the schema descriptor for last_modified_at field.
	questDescLastModifiedAt := questMixinFields0[1].Descriptor()
	// quest.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	quest.DefaultLastModifiedAt = questDescLastModifiedAt.Default.(func() time.Time)
	// quest.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	quest.UpdateDefaultLastModifiedAt = questDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// questDescName is the schema descriptor for name field.
	questDescName := questFields[0].Descriptor()
	// quest.NameValidator is a validator for the "name" field. It is called by the builders before save.
	quest.NameValidator = questDescName.Validators[0].(func(string) error)
	// questDescParameters is the schema descriptor for parameters field.
	questDescParameters := questFields[1].Descriptor()
	// quest.ParametersValidator is a validator for the "parameters" field. It is called by the builders before save.
	quest.ParametersValidator = questDescParameters.Validators[0].(func(string) error)
	// questDescParamDefsAtCreation is the schema descriptor for param_defs_at_creation field.
	questDescParamDefsAtCreation := questFields[2].Descriptor()
	// quest.ParamDefsAtCreationValidator is a validator for the "param_defs_at_creation" field. It is called by the builders before save.
	quest.ParamDefsAtCreationValidator = questDescParamDefsAtCreation.Validators[0].(func(string) error)
	repositoryMixin := schema.Repository{}.Mixin()
	repositoryHooks := schema.Repository{}.Hooks()
	repository.Hooks[0] = repositoryHooks[0]
	repositoryMixinFields0 := repositoryMixin[0].Fields()
	_ = repositoryMixinFields0
	repositoryFields := schema.Repository{}.Fields()
	_ = repositoryFields
	// repositoryDescCreatedAt is the schema descriptor for created_at field.
	repositoryDescCreatedAt := repositoryMixinFields0[0].Descriptor()
	// repository.DefaultCreatedAt holds the default value on creation for the created_at field.
	repository.DefaultCreatedAt = repositoryDescCreatedAt.Default.(func() time.Time)
	// repositoryDescLastModifiedAt is the schema descriptor for last_modified_at field.
	repositoryDescLastModifiedAt := repositoryMixinFields0[1].Descriptor()
	// repository.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	repository.DefaultLastModifiedAt = repositoryDescLastModifiedAt.Default.(func() time.Time)
	// repository.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	repository.UpdateDefaultLastModifiedAt = repositoryDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// repositoryDescURL is the schema descriptor for url field.
	repositoryDescURL := repositoryFields[0].Descriptor()
	// repository.URLValidator is a validator for the "url" field. It is called by the builders before save.
	repository.URLValidator = repositoryDescURL.Validators[0].(func(string) error)
	// repositoryDescPublicKey is the schema descriptor for public_key field.
	repositoryDescPublicKey := repositoryFields[1].Descriptor()
	// repository.PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	repository.PublicKeyValidator = repositoryDescPublicKey.Validators[0].(func(string) error)
	// repositoryDescPrivateKey is the schema descriptor for private_key field.
	repositoryDescPrivateKey := repositoryFields[2].Descriptor()
	// repository.PrivateKeyValidator is a validator for the "private_key" field. It is called by the builders before save.
	repository.PrivateKeyValidator = repositoryDescPrivateKey.Validators[0].(func(string) error)
	shellMixin := schema.Shell{}.Mixin()
	shellMixinFields0 := shellMixin[0].Fields()
	_ = shellMixinFields0
	shellFields := schema.Shell{}.Fields()
	_ = shellFields
	// shellDescCreatedAt is the schema descriptor for created_at field.
	shellDescCreatedAt := shellMixinFields0[0].Descriptor()
	// shell.DefaultCreatedAt holds the default value on creation for the created_at field.
	shell.DefaultCreatedAt = shellDescCreatedAt.Default.(func() time.Time)
	// shellDescLastModifiedAt is the schema descriptor for last_modified_at field.
	shellDescLastModifiedAt := shellMixinFields0[1].Descriptor()
	// shell.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	shell.DefaultLastModifiedAt = shellDescLastModifiedAt.Default.(func() time.Time)
	// shell.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	shell.UpdateDefaultLastModifiedAt = shellDescLastModifiedAt.UpdateDefault.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[0].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	taskMixin := schema.Task{}.Mixin()
	taskHooks := schema.Task{}.Hooks()
	task.Hooks[0] = taskHooks[0]
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescLastModifiedAt is the schema descriptor for last_modified_at field.
	taskDescLastModifiedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	task.DefaultLastModifiedAt = taskDescLastModifiedAt.Default.(func() time.Time)
	// task.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	task.UpdateDefaultLastModifiedAt = taskDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// taskDescOutputSize is the schema descriptor for output_size field.
	taskDescOutputSize := taskFields[4].Descriptor()
	// task.DefaultOutputSize holds the default value on creation for the output_size field.
	task.DefaultOutputSize = taskDescOutputSize.Default.(int)
	// task.OutputSizeValidator is a validator for the "output_size" field. It is called by the builders before save.
	task.OutputSizeValidator = taskDescOutputSize.Validators[0].(func(int) error)
	tomeMixin := schema.Tome{}.Mixin()
	tomeHooks := schema.Tome{}.Hooks()
	tome.Hooks[0] = tomeHooks[0]
	tomeMixinFields0 := tomeMixin[0].Fields()
	_ = tomeMixinFields0
	tomeFields := schema.Tome{}.Fields()
	_ = tomeFields
	// tomeDescCreatedAt is the schema descriptor for created_at field.
	tomeDescCreatedAt := tomeMixinFields0[0].Descriptor()
	// tome.DefaultCreatedAt holds the default value on creation for the created_at field.
	tome.DefaultCreatedAt = tomeDescCreatedAt.Default.(func() time.Time)
	// tomeDescLastModifiedAt is the schema descriptor for last_modified_at field.
	tomeDescLastModifiedAt := tomeMixinFields0[1].Descriptor()
	// tome.DefaultLastModifiedAt holds the default value on creation for the last_modified_at field.
	tome.DefaultLastModifiedAt = tomeDescLastModifiedAt.Default.(func() time.Time)
	// tome.UpdateDefaultLastModifiedAt holds the default value on update for the last_modified_at field.
	tome.UpdateDefaultLastModifiedAt = tomeDescLastModifiedAt.UpdateDefault.(func() time.Time)
	// tomeDescName is the schema descriptor for name field.
	tomeDescName := tomeFields[0].Descriptor()
	// tome.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tome.NameValidator = tomeDescName.Validators[0].(func(string) error)
	// tomeDescParamDefs is the schema descriptor for param_defs field.
	tomeDescParamDefs := tomeFields[5].Descriptor()
	// tome.ParamDefsValidator is a validator for the "param_defs" field. It is called by the builders before save.
	tome.ParamDefsValidator = tomeDescParamDefs.Validators[0].(func(string) error)
	// tomeDescHash is the schema descriptor for hash field.
	tomeDescHash := tomeFields[6].Descriptor()
	// tome.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	tome.HashValidator = tomeDescHash.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescSessionToken is the schema descriptor for session_token field.
	userDescSessionToken := userFields[3].Descriptor()
	// user.DefaultSessionToken holds the default value on creation for the session_token field.
	user.DefaultSessionToken = userDescSessionToken.Default.(func() string)
	// user.SessionTokenValidator is a validator for the "session_token" field. It is called by the builders before save.
	user.SessionTokenValidator = userDescSessionToken.Validators[0].(func(string) error)
	// userDescAccessToken is the schema descriptor for access_token field.
	userDescAccessToken := userFields[4].Descriptor()
	// user.DefaultAccessToken holds the default value on creation for the access_token field.
	user.DefaultAccessToken = userDescAccessToken.Default.(func() string)
	// user.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	user.AccessTokenValidator = userDescAccessToken.Validators[0].(func(string) error)
	// userDescIsActivated is the schema descriptor for is_activated field.
	userDescIsActivated := userFields[5].Descriptor()
	// user.DefaultIsActivated holds the default value on creation for the is_activated field.
	user.DefaultIsActivated = userDescIsActivated.Default.(bool)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[6].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
