// Code generated by ent, DO NOT EDIT.

package shellpivot

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the shellpivot type in the database.
	Label = "shell_pivot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastModifiedAt holds the string denoting the last_modified_at field in the database.
	FieldLastModifiedAt = "last_modified_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldStreamID holds the string denoting the stream_id field in the database.
	FieldStreamID = "stream_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldDestination holds the string denoting the destination field in the database.
	FieldDestination = "destination"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// EdgeShell holds the string denoting the shell edge name in mutations.
	EdgeShell = "shell"
	// EdgePortal holds the string denoting the portal edge name in mutations.
	EdgePortal = "portal"
	// EdgeCredential holds the string denoting the credential edge name in mutations.
	EdgeCredential = "credential"
	// Table holds the table name of the shellpivot in the database.
	Table = "shell_pivots"
	// ShellTable is the table that holds the shell relation/edge.
	ShellTable = "shell_pivots"
	// ShellInverseTable is the table name for the Shell entity.
	// It exists in this package in order to avoid circular dependency with the "shell" package.
	ShellInverseTable = "shells"
	// ShellColumn is the table column denoting the shell relation/edge.
	ShellColumn = "shell_pivot_shell"
	// PortalTable is the table that holds the portal relation/edge.
	PortalTable = "shell_pivots"
	// PortalInverseTable is the table name for the Portal entity.
	// It exists in this package in order to avoid circular dependency with the "portal" package.
	PortalInverseTable = "portals"
	// PortalColumn is the table column denoting the portal relation/edge.
	PortalColumn = "shell_pivot_portal"
	// CredentialTable is the table that holds the credential relation/edge.
	CredentialTable = "shell_pivots"
	// CredentialInverseTable is the table name for the HostCredential entity.
	// It exists in this package in order to avoid circular dependency with the "hostcredential" package.
	CredentialInverseTable = "host_credentials"
	// CredentialColumn is the table column denoting the credential relation/edge.
	CredentialColumn = "shell_pivot_credential"
)

// Columns holds all SQL columns for shellpivot fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldLastModifiedAt,
	FieldClosedAt,
	FieldStreamID,
	FieldKind,
	FieldDestination,
	FieldPort,
	FieldData,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "shell_pivots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"shell_pivot_shell",
	"shell_pivot_portal",
	"shell_pivot_credential",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultLastModifiedAt holds the default value on creation for the "last_modified_at" field.
	DefaultLastModifiedAt func() time.Time
	// UpdateDefaultLastModifiedAt holds the default value on update for the "last_modified_at" field.
	UpdateDefaultLastModifiedAt func() time.Time
	// StreamIDValidator is a validator for the "stream_id" field. It is called by the builders before save.
	StreamIDValidator func(string) error
	// DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	DestinationValidator func(string) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindSSH Kind = "ssh"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindSSH:
		return nil
	default:
		return fmt.Errorf("shellpivot: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the ShellPivot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastModifiedAt orders the results by the last_modified_at field.
func ByLastModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastModifiedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByStreamID orders the results by the stream_id field.
func ByStreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreamID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByDestination orders the results by the destination field.
func ByDestination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestination, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByData orders the results by the data field.
func ByData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldData, opts...).ToFunc()
}

// ByShellField orders the results by shell field.
func ByShellField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShellStep(), sql.OrderByField(field, opts...))
	}
}

// ByPortalField orders the results by portal field.
func ByPortalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPortalStep(), sql.OrderByField(field, opts...))
	}
}

// ByCredentialField orders the results by credential field.
func ByCredentialField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialStep(), sql.OrderByField(field, opts...))
	}
}
func newShellStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShellInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ShellTable, ShellColumn),
	)
}
func newPortalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PortalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PortalTable, PortalColumn),
	)
}
func newCredentialStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CredentialTable, CredentialColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Kind) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Kind) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Kind(str)
	if err := KindValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Kind", str)
	}
	return nil
}
