// Code generated by ent, DO NOT EDIT.

package builder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the builder type in the database.
	Label = "builder"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastModifiedAt holds the string denoting the last_modified_at field in the database.
	FieldLastModifiedAt = "last_modified_at"
	// FieldIdentifier holds the string denoting the identifier field in the database.
	FieldIdentifier = "identifier"
	// FieldSupportedTargets holds the string denoting the supported_targets field in the database.
	FieldSupportedTargets = "supported_targets"
	// FieldUpstream holds the string denoting the upstream field in the database.
	FieldUpstream = "upstream"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// EdgeBuildTasks holds the string denoting the build_tasks edge name in mutations.
	EdgeBuildTasks = "build_tasks"
	// Table holds the table name of the builder in the database.
	Table = "builders"
	// BuildTasksTable is the table that holds the build_tasks relation/edge.
	BuildTasksTable = "build_tasks"
	// BuildTasksInverseTable is the table name for the BuildTask entity.
	// It exists in this package in order to avoid circular dependency with the "buildtask" package.
	BuildTasksInverseTable = "build_tasks"
	// BuildTasksColumn is the table column denoting the build_tasks relation/edge.
	BuildTasksColumn = "build_task_builder"
)

// Columns holds all SQL columns for builder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldLastModifiedAt,
	FieldIdentifier,
	FieldSupportedTargets,
	FieldUpstream,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultLastModifiedAt holds the default value on creation for the "last_modified_at" field.
	DefaultLastModifiedAt func() time.Time
	// UpdateDefaultLastModifiedAt holds the default value on update for the "last_modified_at" field.
	UpdateDefaultLastModifiedAt func() time.Time
	// DefaultIdentifier holds the default value on creation for the "identifier" field.
	DefaultIdentifier func() string
	// IdentifierValidator is a validator for the "identifier" field. It is called by the builders before save.
	IdentifierValidator func(string) error
	// DefaultUpstream holds the default value on creation for the "upstream" field.
	DefaultUpstream string
)

// OrderOption defines the ordering options for the Builder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastModifiedAt orders the results by the last_modified_at field.
func ByLastModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastModifiedAt, opts...).ToFunc()
}

// ByIdentifier orders the results by the identifier field.
func ByIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentifier, opts...).ToFunc()
}

// ByUpstream orders the results by the upstream field.
func ByUpstream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstream, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByBuildTasksCount orders the results by build_tasks count.
func ByBuildTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBuildTasksStep(), opts...)
	}
}

// ByBuildTasks orders the results by build_tasks terms.
func ByBuildTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBuildTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBuildTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BuildTasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, BuildTasksTable, BuildTasksColumn),
	)
}
