// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"realm.pub/tavern/internal/ent/buildprofile"
	"realm.pub/tavern/internal/ent/buildtask"
	"realm.pub/tavern/internal/ent/predicate"
)

// BuildProfileQuery is the builder for querying BuildProfile entities.
type BuildProfileQuery struct {
	config
	ctx                 *QueryContext
	order               []buildprofile.OrderOption
	inters              []Interceptor
	predicates          []predicate.BuildProfile
	withBuildtasks      *BuildTaskQuery
	modifiers           []func(*sql.Selector)
	loadTotal           []func(context.Context, []*BuildProfile) error
	withNamedBuildtasks map[string]*BuildTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BuildProfileQuery builder.
func (bpq *BuildProfileQuery) Where(ps ...predicate.BuildProfile) *BuildProfileQuery {
	bpq.predicates = append(bpq.predicates, ps...)
	return bpq
}

// Limit the number of records to be returned by this query.
func (bpq *BuildProfileQuery) Limit(limit int) *BuildProfileQuery {
	bpq.ctx.Limit = &limit
	return bpq
}

// Offset to start from.
func (bpq *BuildProfileQuery) Offset(offset int) *BuildProfileQuery {
	bpq.ctx.Offset = &offset
	return bpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bpq *BuildProfileQuery) Unique(unique bool) *BuildProfileQuery {
	bpq.ctx.Unique = &unique
	return bpq
}

// Order specifies how the records should be ordered.
func (bpq *BuildProfileQuery) Order(o ...buildprofile.OrderOption) *BuildProfileQuery {
	bpq.order = append(bpq.order, o...)
	return bpq
}

// QueryBuildtasks chains the current query on the "buildtasks" edge.
func (bpq *BuildProfileQuery) QueryBuildtasks() *BuildTaskQuery {
	query := (&BuildTaskClient{config: bpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(buildprofile.Table, buildprofile.FieldID, selector),
			sqlgraph.To(buildtask.Table, buildtask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, buildprofile.BuildtasksTable, buildprofile.BuildtasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(bpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BuildProfile entity from the query.
// Returns a *NotFoundError when no BuildProfile was found.
func (bpq *BuildProfileQuery) First(ctx context.Context) (*BuildProfile, error) {
	nodes, err := bpq.Limit(1).All(setContextOp(ctx, bpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{buildprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bpq *BuildProfileQuery) FirstX(ctx context.Context) *BuildProfile {
	node, err := bpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BuildProfile ID from the query.
// Returns a *NotFoundError when no BuildProfile ID was found.
func (bpq *BuildProfileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bpq.Limit(1).IDs(setContextOp(ctx, bpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{buildprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bpq *BuildProfileQuery) FirstIDX(ctx context.Context) int {
	id, err := bpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BuildProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BuildProfile entity is found.
// Returns a *NotFoundError when no BuildProfile entities are found.
func (bpq *BuildProfileQuery) Only(ctx context.Context) (*BuildProfile, error) {
	nodes, err := bpq.Limit(2).All(setContextOp(ctx, bpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{buildprofile.Label}
	default:
		return nil, &NotSingularError{buildprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bpq *BuildProfileQuery) OnlyX(ctx context.Context) *BuildProfile {
	node, err := bpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BuildProfile ID in the query.
// Returns a *NotSingularError when more than one BuildProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (bpq *BuildProfileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bpq.Limit(2).IDs(setContextOp(ctx, bpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{buildprofile.Label}
	default:
		err = &NotSingularError{buildprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bpq *BuildProfileQuery) OnlyIDX(ctx context.Context) int {
	id, err := bpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BuildProfiles.
func (bpq *BuildProfileQuery) All(ctx context.Context) ([]*BuildProfile, error) {
	ctx = setContextOp(ctx, bpq.ctx, ent.OpQueryAll)
	if err := bpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BuildProfile, *BuildProfileQuery]()
	return withInterceptors[[]*BuildProfile](ctx, bpq, qr, bpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bpq *BuildProfileQuery) AllX(ctx context.Context) []*BuildProfile {
	nodes, err := bpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BuildProfile IDs.
func (bpq *BuildProfileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bpq.ctx.Unique == nil && bpq.path != nil {
		bpq.Unique(true)
	}
	ctx = setContextOp(ctx, bpq.ctx, ent.OpQueryIDs)
	if err = bpq.Select(buildprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bpq *BuildProfileQuery) IDsX(ctx context.Context) []int {
	ids, err := bpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bpq *BuildProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bpq.ctx, ent.OpQueryCount)
	if err := bpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bpq, querierCount[*BuildProfileQuery](), bpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bpq *BuildProfileQuery) CountX(ctx context.Context) int {
	count, err := bpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bpq *BuildProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bpq.ctx, ent.OpQueryExist)
	switch _, err := bpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bpq *BuildProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := bpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BuildProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bpq *BuildProfileQuery) Clone() *BuildProfileQuery {
	if bpq == nil {
		return nil
	}
	return &BuildProfileQuery{
		config:         bpq.config,
		ctx:            bpq.ctx.Clone(),
		order:          append([]buildprofile.OrderOption{}, bpq.order...),
		inters:         append([]Interceptor{}, bpq.inters...),
		predicates:     append([]predicate.BuildProfile{}, bpq.predicates...),
		withBuildtasks: bpq.withBuildtasks.Clone(),
		// clone intermediate query.
		sql:  bpq.sql.Clone(),
		path: bpq.path,
	}
}

// WithBuildtasks tells the query-builder to eager-load the nodes that are connected to
// the "buildtasks" edge. The optional arguments are used to configure the query builder of the edge.
func (bpq *BuildProfileQuery) WithBuildtasks(opts ...func(*BuildTaskQuery)) *BuildProfileQuery {
	query := (&BuildTaskClient{config: bpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bpq.withBuildtasks = query
	return bpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BuildProfile.Query().
//		GroupBy(buildprofile.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bpq *BuildProfileQuery) GroupBy(field string, fields ...string) *BuildProfileGroupBy {
	bpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BuildProfileGroupBy{build: bpq}
	grbuild.flds = &bpq.ctx.Fields
	grbuild.label = buildprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.BuildProfile.Query().
//		Select(buildprofile.FieldName).
//		Scan(ctx, &v)
func (bpq *BuildProfileQuery) Select(fields ...string) *BuildProfileSelect {
	bpq.ctx.Fields = append(bpq.ctx.Fields, fields...)
	sbuild := &BuildProfileSelect{BuildProfileQuery: bpq}
	sbuild.label = buildprofile.Label
	sbuild.flds, sbuild.scan = &bpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BuildProfileSelect configured with the given aggregations.
func (bpq *BuildProfileQuery) Aggregate(fns ...AggregateFunc) *BuildProfileSelect {
	return bpq.Select().Aggregate(fns...)
}

func (bpq *BuildProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bpq); err != nil {
				return err
			}
		}
	}
	for _, f := range bpq.ctx.Fields {
		if !buildprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bpq.path != nil {
		prev, err := bpq.path(ctx)
		if err != nil {
			return err
		}
		bpq.sql = prev
	}
	return nil
}

func (bpq *BuildProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BuildProfile, error) {
	var (
		nodes       = []*BuildProfile{}
		_spec       = bpq.querySpec()
		loadedTypes = [1]bool{
			bpq.withBuildtasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BuildProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BuildProfile{config: bpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(bpq.modifiers) > 0 {
		_spec.Modifiers = bpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bpq.withBuildtasks; query != nil {
		if err := bpq.loadBuildtasks(ctx, query, nodes,
			func(n *BuildProfile) { n.Edges.Buildtasks = []*BuildTask{} },
			func(n *BuildProfile, e *BuildTask) { n.Edges.Buildtasks = append(n.Edges.Buildtasks, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range bpq.withNamedBuildtasks {
		if err := bpq.loadBuildtasks(ctx, query, nodes,
			func(n *BuildProfile) { n.appendNamedBuildtasks(name) },
			func(n *BuildProfile, e *BuildTask) { n.appendNamedBuildtasks(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range bpq.loadTotal {
		if err := bpq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bpq *BuildProfileQuery) loadBuildtasks(ctx context.Context, query *BuildTaskQuery, nodes []*BuildProfile, init func(*BuildProfile), assign func(*BuildProfile, *BuildTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*BuildProfile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BuildTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(buildprofile.BuildtasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.build_task_profile
		if fk == nil {
			return fmt.Errorf(`foreign-key "build_task_profile" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "build_task_profile" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bpq *BuildProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bpq.querySpec()
	if len(bpq.modifiers) > 0 {
		_spec.Modifiers = bpq.modifiers
	}
	_spec.Node.Columns = bpq.ctx.Fields
	if len(bpq.ctx.Fields) > 0 {
		_spec.Unique = bpq.ctx.Unique != nil && *bpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bpq.driver, _spec)
}

func (bpq *BuildProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(buildprofile.Table, buildprofile.Columns, sqlgraph.NewFieldSpec(buildprofile.FieldID, field.TypeInt))
	_spec.From = bpq.sql
	if unique := bpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bpq.path != nil {
		_spec.Unique = true
	}
	if fields := bpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, buildprofile.FieldID)
		for i := range fields {
			if fields[i] != buildprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bpq *BuildProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bpq.driver.Dialect())
	t1 := builder.Table(buildprofile.Table)
	columns := bpq.ctx.Fields
	if len(columns) == 0 {
		columns = buildprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bpq.sql != nil {
		selector = bpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bpq.ctx.Unique != nil && *bpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bpq.predicates {
		p(selector)
	}
	for _, p := range bpq.order {
		p(selector)
	}
	if offset := bpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedBuildtasks tells the query-builder to eager-load the nodes that are connected to the "buildtasks"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (bpq *BuildProfileQuery) WithNamedBuildtasks(name string, opts ...func(*BuildTaskQuery)) *BuildProfileQuery {
	query := (&BuildTaskClient{config: bpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if bpq.withNamedBuildtasks == nil {
		bpq.withNamedBuildtasks = make(map[string]*BuildTaskQuery)
	}
	bpq.withNamedBuildtasks[name] = query
	return bpq
}

// BuildProfileGroupBy is the group-by builder for BuildProfile entities.
type BuildProfileGroupBy struct {
	selector
	build *BuildProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bpgb *BuildProfileGroupBy) Aggregate(fns ...AggregateFunc) *BuildProfileGroupBy {
	bpgb.fns = append(bpgb.fns, fns...)
	return bpgb
}

// Scan applies the selector query and scans the result into the given value.
func (bpgb *BuildProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bpgb.build.ctx, ent.OpQueryGroupBy)
	if err := bpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BuildProfileQuery, *BuildProfileGroupBy](ctx, bpgb.build, bpgb, bpgb.build.inters, v)
}

func (bpgb *BuildProfileGroupBy) sqlScan(ctx context.Context, root *BuildProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bpgb.fns))
	for _, fn := range bpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bpgb.flds)+len(bpgb.fns))
		for _, f := range *bpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BuildProfileSelect is the builder for selecting fields of BuildProfile entities.
type BuildProfileSelect struct {
	*BuildProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bps *BuildProfileSelect) Aggregate(fns ...AggregateFunc) *BuildProfileSelect {
	bps.fns = append(bps.fns, fns...)
	return bps
}

// Scan applies the selector query and scans the result into the given value.
func (bps *BuildProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bps.ctx, ent.OpQuerySelect)
	if err := bps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BuildProfileQuery, *BuildProfileSelect](ctx, bps.BuildProfileQuery, bps, bps.inters, v)
}

func (bps *BuildProfileSelect) sqlScan(ctx context.Context, root *BuildProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bps.fns))
	for _, fn := range bps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
