// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"realm.pub/tavern/internal/c2/c2pb"
	"realm.pub/tavern/internal/ent/builder"
	"realm.pub/tavern/internal/ent/buildtask"
)

// BuildTaskCreate is the builder for creating a BuildTask entity.
type BuildTaskCreate struct {
	config
	mutation *BuildTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (btc *BuildTaskCreate) SetCreatedAt(t time.Time) *BuildTaskCreate {
	btc.mutation.SetCreatedAt(t)
	return btc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableCreatedAt(t *time.Time) *BuildTaskCreate {
	if t != nil {
		btc.SetCreatedAt(*t)
	}
	return btc
}

// SetLastModifiedAt sets the "last_modified_at" field.
func (btc *BuildTaskCreate) SetLastModifiedAt(t time.Time) *BuildTaskCreate {
	btc.mutation.SetLastModifiedAt(t)
	return btc
}

// SetNillableLastModifiedAt sets the "last_modified_at" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableLastModifiedAt(t *time.Time) *BuildTaskCreate {
	if t != nil {
		btc.SetLastModifiedAt(*t)
	}
	return btc
}

// SetTargetOs sets the "target_os" field.
func (btc *BuildTaskCreate) SetTargetOs(cp c2pb.Host_Platform) *BuildTaskCreate {
	btc.mutation.SetTargetOs(cp)
	return btc
}

// SetBuildImage sets the "build_image" field.
func (btc *BuildTaskCreate) SetBuildImage(s string) *BuildTaskCreate {
	btc.mutation.SetBuildImage(s)
	return btc
}

// SetBuildScript sets the "build_script" field.
func (btc *BuildTaskCreate) SetBuildScript(s string) *BuildTaskCreate {
	btc.mutation.SetBuildScript(s)
	return btc
}

// SetClaimedAt sets the "claimed_at" field.
func (btc *BuildTaskCreate) SetClaimedAt(t time.Time) *BuildTaskCreate {
	btc.mutation.SetClaimedAt(t)
	return btc
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableClaimedAt(t *time.Time) *BuildTaskCreate {
	if t != nil {
		btc.SetClaimedAt(*t)
	}
	return btc
}

// SetStartedAt sets the "started_at" field.
func (btc *BuildTaskCreate) SetStartedAt(t time.Time) *BuildTaskCreate {
	btc.mutation.SetStartedAt(t)
	return btc
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableStartedAt(t *time.Time) *BuildTaskCreate {
	if t != nil {
		btc.SetStartedAt(*t)
	}
	return btc
}

// SetFinishedAt sets the "finished_at" field.
func (btc *BuildTaskCreate) SetFinishedAt(t time.Time) *BuildTaskCreate {
	btc.mutation.SetFinishedAt(t)
	return btc
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableFinishedAt(t *time.Time) *BuildTaskCreate {
	if t != nil {
		btc.SetFinishedAt(*t)
	}
	return btc
}

// SetOutput sets the "output" field.
func (btc *BuildTaskCreate) SetOutput(s string) *BuildTaskCreate {
	btc.mutation.SetOutput(s)
	return btc
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableOutput(s *string) *BuildTaskCreate {
	if s != nil {
		btc.SetOutput(*s)
	}
	return btc
}

// SetOutputSize sets the "output_size" field.
func (btc *BuildTaskCreate) SetOutputSize(i int) *BuildTaskCreate {
	btc.mutation.SetOutputSize(i)
	return btc
}

// SetNillableOutputSize sets the "output_size" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableOutputSize(i *int) *BuildTaskCreate {
	if i != nil {
		btc.SetOutputSize(*i)
	}
	return btc
}

// SetError sets the "error" field.
func (btc *BuildTaskCreate) SetError(s string) *BuildTaskCreate {
	btc.mutation.SetError(s)
	return btc
}

// SetNillableError sets the "error" field if the given value is not nil.
func (btc *BuildTaskCreate) SetNillableError(s *string) *BuildTaskCreate {
	if s != nil {
		btc.SetError(*s)
	}
	return btc
}

// SetBuilderID sets the "builder" edge to the Builder entity by ID.
func (btc *BuildTaskCreate) SetBuilderID(id int) *BuildTaskCreate {
	btc.mutation.SetBuilderID(id)
	return btc
}

// SetBuilder sets the "builder" edge to the Builder entity.
func (btc *BuildTaskCreate) SetBuilder(b *Builder) *BuildTaskCreate {
	return btc.SetBuilderID(b.ID)
}

// Mutation returns the BuildTaskMutation object of the builder.
func (btc *BuildTaskCreate) Mutation() *BuildTaskMutation {
	return btc.mutation
}

// Save creates the BuildTask in the database.
func (btc *BuildTaskCreate) Save(ctx context.Context) (*BuildTask, error) {
	if err := btc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, btc.sqlSave, btc.mutation, btc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (btc *BuildTaskCreate) SaveX(ctx context.Context) *BuildTask {
	v, err := btc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (btc *BuildTaskCreate) Exec(ctx context.Context) error {
	_, err := btc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (btc *BuildTaskCreate) ExecX(ctx context.Context) {
	if err := btc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (btc *BuildTaskCreate) defaults() error {
	if _, ok := btc.mutation.CreatedAt(); !ok {
		if buildtask.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized buildtask.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := buildtask.DefaultCreatedAt()
		btc.mutation.SetCreatedAt(v)
	}
	if _, ok := btc.mutation.LastModifiedAt(); !ok {
		if buildtask.DefaultLastModifiedAt == nil {
			return fmt.Errorf("ent: uninitialized buildtask.DefaultLastModifiedAt (forgotten import ent/runtime?)")
		}
		v := buildtask.DefaultLastModifiedAt()
		btc.mutation.SetLastModifiedAt(v)
	}
	if _, ok := btc.mutation.OutputSize(); !ok {
		v := buildtask.DefaultOutputSize
		btc.mutation.SetOutputSize(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (btc *BuildTaskCreate) check() error {
	if _, ok := btc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BuildTask.created_at"`)}
	}
	if _, ok := btc.mutation.LastModifiedAt(); !ok {
		return &ValidationError{Name: "last_modified_at", err: errors.New(`ent: missing required field "BuildTask.last_modified_at"`)}
	}
	if _, ok := btc.mutation.TargetOs(); !ok {
		return &ValidationError{Name: "target_os", err: errors.New(`ent: missing required field "BuildTask.target_os"`)}
	}
	if v, ok := btc.mutation.TargetOs(); ok {
		if err := buildtask.TargetOsValidator(v); err != nil {
			return &ValidationError{Name: "target_os", err: fmt.Errorf(`ent: validator failed for field "BuildTask.target_os": %w`, err)}
		}
	}
	if _, ok := btc.mutation.BuildImage(); !ok {
		return &ValidationError{Name: "build_image", err: errors.New(`ent: missing required field "BuildTask.build_image"`)}
	}
	if v, ok := btc.mutation.BuildImage(); ok {
		if err := buildtask.BuildImageValidator(v); err != nil {
			return &ValidationError{Name: "build_image", err: fmt.Errorf(`ent: validator failed for field "BuildTask.build_image": %w`, err)}
		}
	}
	if _, ok := btc.mutation.BuildScript(); !ok {
		return &ValidationError{Name: "build_script", err: errors.New(`ent: missing required field "BuildTask.build_script"`)}
	}
	if v, ok := btc.mutation.BuildScript(); ok {
		if err := buildtask.BuildScriptValidator(v); err != nil {
			return &ValidationError{Name: "build_script", err: fmt.Errorf(`ent: validator failed for field "BuildTask.build_script": %w`, err)}
		}
	}
	if _, ok := btc.mutation.OutputSize(); !ok {
		return &ValidationError{Name: "output_size", err: errors.New(`ent: missing required field "BuildTask.output_size"`)}
	}
	if v, ok := btc.mutation.OutputSize(); ok {
		if err := buildtask.OutputSizeValidator(v); err != nil {
			return &ValidationError{Name: "output_size", err: fmt.Errorf(`ent: validator failed for field "BuildTask.output_size": %w`, err)}
		}
	}
	if len(btc.mutation.BuilderIDs()) == 0 {
		return &ValidationError{Name: "builder", err: errors.New(`ent: missing required edge "BuildTask.builder"`)}
	}
	return nil
}

func (btc *BuildTaskCreate) sqlSave(ctx context.Context) (*BuildTask, error) {
	if err := btc.check(); err != nil {
		return nil, err
	}
	_node, _spec := btc.createSpec()
	if err := sqlgraph.CreateNode(ctx, btc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	btc.mutation.id = &_node.ID
	btc.mutation.done = true
	return _node, nil
}

func (btc *BuildTaskCreate) createSpec() (*BuildTask, *sqlgraph.CreateSpec) {
	var (
		_node = &BuildTask{config: btc.config}
		_spec = sqlgraph.NewCreateSpec(buildtask.Table, sqlgraph.NewFieldSpec(buildtask.FieldID, field.TypeInt))
	)
	_spec.OnConflict = btc.conflict
	if value, ok := btc.mutation.CreatedAt(); ok {
		_spec.SetField(buildtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := btc.mutation.LastModifiedAt(); ok {
		_spec.SetField(buildtask.FieldLastModifiedAt, field.TypeTime, value)
		_node.LastModifiedAt = value
	}
	if value, ok := btc.mutation.TargetOs(); ok {
		_spec.SetField(buildtask.FieldTargetOs, field.TypeEnum, value)
		_node.TargetOs = value
	}
	if value, ok := btc.mutation.BuildImage(); ok {
		_spec.SetField(buildtask.FieldBuildImage, field.TypeString, value)
		_node.BuildImage = value
	}
	if value, ok := btc.mutation.BuildScript(); ok {
		_spec.SetField(buildtask.FieldBuildScript, field.TypeString, value)
		_node.BuildScript = value
	}
	if value, ok := btc.mutation.ClaimedAt(); ok {
		_spec.SetField(buildtask.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = value
	}
	if value, ok := btc.mutation.StartedAt(); ok {
		_spec.SetField(buildtask.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := btc.mutation.FinishedAt(); ok {
		_spec.SetField(buildtask.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := btc.mutation.Output(); ok {
		_spec.SetField(buildtask.FieldOutput, field.TypeString, value)
		_node.Output = value
	}
	if value, ok := btc.mutation.OutputSize(); ok {
		_spec.SetField(buildtask.FieldOutputSize, field.TypeInt, value)
		_node.OutputSize = value
	}
	if value, ok := btc.mutation.Error(); ok {
		_spec.SetField(buildtask.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if nodes := btc.mutation.BuilderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   buildtask.BuilderTable,
			Columns: []string{buildtask.BuilderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(builder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.build_task_builder = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BuildTask.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuildTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (btc *BuildTaskCreate) OnConflict(opts ...sql.ConflictOption) *BuildTaskUpsertOne {
	btc.conflict = opts
	return &BuildTaskUpsertOne{
		create: btc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BuildTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (btc *BuildTaskCreate) OnConflictColumns(columns ...string) *BuildTaskUpsertOne {
	btc.conflict = append(btc.conflict, sql.ConflictColumns(columns...))
	return &BuildTaskUpsertOne{
		create: btc,
	}
}

type (
	// BuildTaskUpsertOne is the builder for "upsert"-ing
	//  one BuildTask node.
	BuildTaskUpsertOne struct {
		create *BuildTaskCreate
	}

	// BuildTaskUpsert is the "OnConflict" setter.
	BuildTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetLastModifiedAt sets the "last_modified_at" field.
func (u *BuildTaskUpsert) SetLastModifiedAt(v time.Time) *BuildTaskUpsert {
	u.Set(buildtask.FieldLastModifiedAt, v)
	return u
}

// UpdateLastModifiedAt sets the "last_modified_at" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateLastModifiedAt() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldLastModifiedAt)
	return u
}

// SetTargetOs sets the "target_os" field.
func (u *BuildTaskUpsert) SetTargetOs(v c2pb.Host_Platform) *BuildTaskUpsert {
	u.Set(buildtask.FieldTargetOs, v)
	return u
}

// UpdateTargetOs sets the "target_os" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateTargetOs() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldTargetOs)
	return u
}

// SetBuildImage sets the "build_image" field.
func (u *BuildTaskUpsert) SetBuildImage(v string) *BuildTaskUpsert {
	u.Set(buildtask.FieldBuildImage, v)
	return u
}

// UpdateBuildImage sets the "build_image" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateBuildImage() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldBuildImage)
	return u
}

// SetBuildScript sets the "build_script" field.
func (u *BuildTaskUpsert) SetBuildScript(v string) *BuildTaskUpsert {
	u.Set(buildtask.FieldBuildScript, v)
	return u
}

// UpdateBuildScript sets the "build_script" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateBuildScript() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldBuildScript)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BuildTaskUpsert) SetClaimedAt(v time.Time) *BuildTaskUpsert {
	u.Set(buildtask.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateClaimedAt() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldClaimedAt)
	return u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *BuildTaskUpsert) ClearClaimedAt() *BuildTaskUpsert {
	u.SetNull(buildtask.FieldClaimedAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *BuildTaskUpsert) SetStartedAt(v time.Time) *BuildTaskUpsert {
	u.Set(buildtask.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateStartedAt() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *BuildTaskUpsert) ClearStartedAt() *BuildTaskUpsert {
	u.SetNull(buildtask.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *BuildTaskUpsert) SetFinishedAt(v time.Time) *BuildTaskUpsert {
	u.Set(buildtask.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateFinishedAt() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *BuildTaskUpsert) ClearFinishedAt() *BuildTaskUpsert {
	u.SetNull(buildtask.FieldFinishedAt)
	return u
}

// SetOutput sets the "output" field.
func (u *BuildTaskUpsert) SetOutput(v string) *BuildTaskUpsert {
	u.Set(buildtask.FieldOutput, v)
	return u
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateOutput() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldOutput)
	return u
}

// ClearOutput clears the value of the "output" field.
func (u *BuildTaskUpsert) ClearOutput() *BuildTaskUpsert {
	u.SetNull(buildtask.FieldOutput)
	return u
}

// SetOutputSize sets the "output_size" field.
func (u *BuildTaskUpsert) SetOutputSize(v int) *BuildTaskUpsert {
	u.Set(buildtask.FieldOutputSize, v)
	return u
}

// UpdateOutputSize sets the "output_size" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateOutputSize() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldOutputSize)
	return u
}

// AddOutputSize adds v to the "output_size" field.
func (u *BuildTaskUpsert) AddOutputSize(v int) *BuildTaskUpsert {
	u.Add(buildtask.FieldOutputSize, v)
	return u
}

// SetError sets the "error" field.
func (u *BuildTaskUpsert) SetError(v string) *BuildTaskUpsert {
	u.Set(buildtask.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *BuildTaskUpsert) UpdateError() *BuildTaskUpsert {
	u.SetExcluded(buildtask.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *BuildTaskUpsert) ClearError() *BuildTaskUpsert {
	u.SetNull(buildtask.FieldError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BuildTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuildTaskUpsertOne) UpdateNewValues() *BuildTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(buildtask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BuildTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BuildTaskUpsertOne) Ignore() *BuildTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuildTaskUpsertOne) DoNothing() *BuildTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuildTaskCreate.OnConflict
// documentation for more info.
func (u *BuildTaskUpsertOne) Update(set func(*BuildTaskUpsert)) *BuildTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuildTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastModifiedAt sets the "last_modified_at" field.
func (u *BuildTaskUpsertOne) SetLastModifiedAt(v time.Time) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetLastModifiedAt(v)
	})
}

// UpdateLastModifiedAt sets the "last_modified_at" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateLastModifiedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateLastModifiedAt()
	})
}

// SetTargetOs sets the "target_os" field.
func (u *BuildTaskUpsertOne) SetTargetOs(v c2pb.Host_Platform) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetTargetOs(v)
	})
}

// UpdateTargetOs sets the "target_os" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateTargetOs() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateTargetOs()
	})
}

// SetBuildImage sets the "build_image" field.
func (u *BuildTaskUpsertOne) SetBuildImage(v string) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetBuildImage(v)
	})
}

// UpdateBuildImage sets the "build_image" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateBuildImage() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateBuildImage()
	})
}

// SetBuildScript sets the "build_script" field.
func (u *BuildTaskUpsertOne) SetBuildScript(v string) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetBuildScript(v)
	})
}

// UpdateBuildScript sets the "build_script" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateBuildScript() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateBuildScript()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BuildTaskUpsertOne) SetClaimedAt(v time.Time) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateClaimedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *BuildTaskUpsertOne) ClearClaimedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearClaimedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *BuildTaskUpsertOne) SetStartedAt(v time.Time) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateStartedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *BuildTaskUpsertOne) ClearStartedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *BuildTaskUpsertOne) SetFinishedAt(v time.Time) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateFinishedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *BuildTaskUpsertOne) ClearFinishedAt() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetOutput sets the "output" field.
func (u *BuildTaskUpsertOne) SetOutput(v string) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateOutput() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *BuildTaskUpsertOne) ClearOutput() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearOutput()
	})
}

// SetOutputSize sets the "output_size" field.
func (u *BuildTaskUpsertOne) SetOutputSize(v int) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetOutputSize(v)
	})
}

// AddOutputSize adds v to the "output_size" field.
func (u *BuildTaskUpsertOne) AddOutputSize(v int) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.AddOutputSize(v)
	})
}

// UpdateOutputSize sets the "output_size" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateOutputSize() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateOutputSize()
	})
}

// SetError sets the "error" field.
func (u *BuildTaskUpsertOne) SetError(v string) *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *BuildTaskUpsertOne) UpdateError() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *BuildTaskUpsertOne) ClearError() *BuildTaskUpsertOne {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *BuildTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuildTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuildTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BuildTaskUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BuildTaskUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BuildTaskCreateBulk is the builder for creating many BuildTask entities in bulk.
type BuildTaskCreateBulk struct {
	config
	err      error
	builders []*BuildTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the BuildTask entities in the database.
func (btcb *BuildTaskCreateBulk) Save(ctx context.Context) ([]*BuildTask, error) {
	if btcb.err != nil {
		return nil, btcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(btcb.builders))
	nodes := make([]*BuildTask, len(btcb.builders))
	mutators := make([]Mutator, len(btcb.builders))
	for i := range btcb.builders {
		func(i int, root context.Context) {
			builder := btcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BuildTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, btcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = btcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, btcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, btcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (btcb *BuildTaskCreateBulk) SaveX(ctx context.Context) []*BuildTask {
	v, err := btcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (btcb *BuildTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := btcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (btcb *BuildTaskCreateBulk) ExecX(ctx context.Context) {
	if err := btcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BuildTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuildTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (btcb *BuildTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *BuildTaskUpsertBulk {
	btcb.conflict = opts
	return &BuildTaskUpsertBulk{
		create: btcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BuildTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (btcb *BuildTaskCreateBulk) OnConflictColumns(columns ...string) *BuildTaskUpsertBulk {
	btcb.conflict = append(btcb.conflict, sql.ConflictColumns(columns...))
	return &BuildTaskUpsertBulk{
		create: btcb,
	}
}

// BuildTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of BuildTask nodes.
type BuildTaskUpsertBulk struct {
	create *BuildTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BuildTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuildTaskUpsertBulk) UpdateNewValues() *BuildTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(buildtask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BuildTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BuildTaskUpsertBulk) Ignore() *BuildTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuildTaskUpsertBulk) DoNothing() *BuildTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuildTaskCreateBulk.OnConflict
// documentation for more info.
func (u *BuildTaskUpsertBulk) Update(set func(*BuildTaskUpsert)) *BuildTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuildTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastModifiedAt sets the "last_modified_at" field.
func (u *BuildTaskUpsertBulk) SetLastModifiedAt(v time.Time) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetLastModifiedAt(v)
	})
}

// UpdateLastModifiedAt sets the "last_modified_at" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateLastModifiedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateLastModifiedAt()
	})
}

// SetTargetOs sets the "target_os" field.
func (u *BuildTaskUpsertBulk) SetTargetOs(v c2pb.Host_Platform) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetTargetOs(v)
	})
}

// UpdateTargetOs sets the "target_os" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateTargetOs() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateTargetOs()
	})
}

// SetBuildImage sets the "build_image" field.
func (u *BuildTaskUpsertBulk) SetBuildImage(v string) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetBuildImage(v)
	})
}

// UpdateBuildImage sets the "build_image" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateBuildImage() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateBuildImage()
	})
}

// SetBuildScript sets the "build_script" field.
func (u *BuildTaskUpsertBulk) SetBuildScript(v string) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetBuildScript(v)
	})
}

// UpdateBuildScript sets the "build_script" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateBuildScript() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateBuildScript()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BuildTaskUpsertBulk) SetClaimedAt(v time.Time) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateClaimedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *BuildTaskUpsertBulk) ClearClaimedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearClaimedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *BuildTaskUpsertBulk) SetStartedAt(v time.Time) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateStartedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *BuildTaskUpsertBulk) ClearStartedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *BuildTaskUpsertBulk) SetFinishedAt(v time.Time) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateFinishedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *BuildTaskUpsertBulk) ClearFinishedAt() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetOutput sets the "output" field.
func (u *BuildTaskUpsertBulk) SetOutput(v string) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateOutput() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *BuildTaskUpsertBulk) ClearOutput() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearOutput()
	})
}

// SetOutputSize sets the "output_size" field.
func (u *BuildTaskUpsertBulk) SetOutputSize(v int) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetOutputSize(v)
	})
}

// AddOutputSize adds v to the "output_size" field.
func (u *BuildTaskUpsertBulk) AddOutputSize(v int) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.AddOutputSize(v)
	})
}

// UpdateOutputSize sets the "output_size" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateOutputSize() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateOutputSize()
	})
}

// SetError sets the "error" field.
func (u *BuildTaskUpsertBulk) SetError(v string) *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *BuildTaskUpsertBulk) UpdateError() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *BuildTaskUpsertBulk) ClearError() *BuildTaskUpsertBulk {
	return u.Update(func(s *BuildTaskUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *BuildTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BuildTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuildTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuildTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
