// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"realm.pub/tavern/internal/c2/c2pb"
	"realm.pub/tavern/internal/ent/builder"
)

// BuilderCreate is the builder for creating a Builder entity.
type BuilderCreate struct {
	config
	mutation *BuilderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (bc *BuilderCreate) SetCreatedAt(t time.Time) *BuilderCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BuilderCreate) SetNillableCreatedAt(t *time.Time) *BuilderCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetLastModifiedAt sets the "last_modified_at" field.
func (bc *BuilderCreate) SetLastModifiedAt(t time.Time) *BuilderCreate {
	bc.mutation.SetLastModifiedAt(t)
	return bc
}

// SetNillableLastModifiedAt sets the "last_modified_at" field if the given value is not nil.
func (bc *BuilderCreate) SetNillableLastModifiedAt(t *time.Time) *BuilderCreate {
	if t != nil {
		bc.SetLastModifiedAt(*t)
	}
	return bc
}

// SetIdentifier sets the "identifier" field.
func (bc *BuilderCreate) SetIdentifier(s string) *BuilderCreate {
	bc.mutation.SetIdentifier(s)
	return bc
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (bc *BuilderCreate) SetNillableIdentifier(s *string) *BuilderCreate {
	if s != nil {
		bc.SetIdentifier(*s)
	}
	return bc
}

// SetSupportedTargets sets the "supported_targets" field.
func (bc *BuilderCreate) SetSupportedTargets(cp []c2pb.Host_Platform) *BuilderCreate {
	bc.mutation.SetSupportedTargets(cp)
	return bc
}

// SetUpstream sets the "upstream" field.
func (bc *BuilderCreate) SetUpstream(s string) *BuilderCreate {
	bc.mutation.SetUpstream(s)
	return bc
}

// Mutation returns the BuilderMutation object of the builder.
func (bc *BuilderCreate) Mutation() *BuilderMutation {
	return bc.mutation
}

// Save creates the Builder in the database.
func (bc *BuilderCreate) Save(ctx context.Context) (*Builder, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BuilderCreate) SaveX(ctx context.Context) *Builder {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BuilderCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BuilderCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BuilderCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := builder.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.LastModifiedAt(); !ok {
		v := builder.DefaultLastModifiedAt()
		bc.mutation.SetLastModifiedAt(v)
	}
	if _, ok := bc.mutation.Identifier(); !ok {
		v := builder.DefaultIdentifier()
		bc.mutation.SetIdentifier(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BuilderCreate) check() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Builder.created_at"`)}
	}
	if _, ok := bc.mutation.LastModifiedAt(); !ok {
		return &ValidationError{Name: "last_modified_at", err: errors.New(`ent: missing required field "Builder.last_modified_at"`)}
	}
	if _, ok := bc.mutation.Identifier(); !ok {
		return &ValidationError{Name: "identifier", err: errors.New(`ent: missing required field "Builder.identifier"`)}
	}
	if v, ok := bc.mutation.Identifier(); ok {
		if err := builder.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Builder.identifier": %w`, err)}
		}
	}
	if _, ok := bc.mutation.SupportedTargets(); !ok {
		return &ValidationError{Name: "supported_targets", err: errors.New(`ent: missing required field "Builder.supported_targets"`)}
	}
	if _, ok := bc.mutation.Upstream(); !ok {
		return &ValidationError{Name: "upstream", err: errors.New(`ent: missing required field "Builder.upstream"`)}
	}
	return nil
}

func (bc *BuilderCreate) sqlSave(ctx context.Context) (*Builder, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BuilderCreate) createSpec() (*Builder, *sqlgraph.CreateSpec) {
	var (
		_node = &Builder{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(builder.Table, sqlgraph.NewFieldSpec(builder.FieldID, field.TypeInt))
	)
	_spec.OnConflict = bc.conflict
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(builder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.LastModifiedAt(); ok {
		_spec.SetField(builder.FieldLastModifiedAt, field.TypeTime, value)
		_node.LastModifiedAt = value
	}
	if value, ok := bc.mutation.Identifier(); ok {
		_spec.SetField(builder.FieldIdentifier, field.TypeString, value)
		_node.Identifier = value
	}
	if value, ok := bc.mutation.SupportedTargets(); ok {
		_spec.SetField(builder.FieldSupportedTargets, field.TypeJSON, value)
		_node.SupportedTargets = value
	}
	if value, ok := bc.mutation.Upstream(); ok {
		_spec.SetField(builder.FieldUpstream, field.TypeString, value)
		_node.Upstream = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Builder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuilderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bc *BuilderCreate) OnConflict(opts ...sql.ConflictOption) *BuilderUpsertOne {
	bc.conflict = opts
	return &BuilderUpsertOne{
		create: bc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Builder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bc *BuilderCreate) OnConflictColumns(columns ...string) *BuilderUpsertOne {
	bc.conflict = append(bc.conflict, sql.ConflictColumns(columns...))
	return &BuilderUpsertOne{
		create: bc,
	}
}

type (
	// BuilderUpsertOne is the builder for "upsert"-ing
	//  one Builder node.
	BuilderUpsertOne struct {
		create *BuilderCreate
	}

	// BuilderUpsert is the "OnConflict" setter.
	BuilderUpsert struct {
		*sql.UpdateSet
	}
)

// SetLastModifiedAt sets the "last_modified_at" field.
func (u *BuilderUpsert) SetLastModifiedAt(v time.Time) *BuilderUpsert {
	u.Set(builder.FieldLastModifiedAt, v)
	return u
}

// UpdateLastModifiedAt sets the "last_modified_at" field to the value that was provided on create.
func (u *BuilderUpsert) UpdateLastModifiedAt() *BuilderUpsert {
	u.SetExcluded(builder.FieldLastModifiedAt)
	return u
}

// SetSupportedTargets sets the "supported_targets" field.
func (u *BuilderUpsert) SetSupportedTargets(v []c2pb.Host_Platform) *BuilderUpsert {
	u.Set(builder.FieldSupportedTargets, v)
	return u
}

// UpdateSupportedTargets sets the "supported_targets" field to the value that was provided on create.
func (u *BuilderUpsert) UpdateSupportedTargets() *BuilderUpsert {
	u.SetExcluded(builder.FieldSupportedTargets)
	return u
}

// SetUpstream sets the "upstream" field.
func (u *BuilderUpsert) SetUpstream(v string) *BuilderUpsert {
	u.Set(builder.FieldUpstream, v)
	return u
}

// UpdateUpstream sets the "upstream" field to the value that was provided on create.
func (u *BuilderUpsert) UpdateUpstream() *BuilderUpsert {
	u.SetExcluded(builder.FieldUpstream)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Builder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuilderUpsertOne) UpdateNewValues() *BuilderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(builder.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Identifier(); exists {
			s.SetIgnore(builder.FieldIdentifier)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Builder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BuilderUpsertOne) Ignore() *BuilderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuilderUpsertOne) DoNothing() *BuilderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuilderCreate.OnConflict
// documentation for more info.
func (u *BuilderUpsertOne) Update(set func(*BuilderUpsert)) *BuilderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuilderUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastModifiedAt sets the "last_modified_at" field.
func (u *BuilderUpsertOne) SetLastModifiedAt(v time.Time) *BuilderUpsertOne {
	return u.Update(func(s *BuilderUpsert) {
		s.SetLastModifiedAt(v)
	})
}

// UpdateLastModifiedAt sets the "last_modified_at" field to the value that was provided on create.
func (u *BuilderUpsertOne) UpdateLastModifiedAt() *BuilderUpsertOne {
	return u.Update(func(s *BuilderUpsert) {
		s.UpdateLastModifiedAt()
	})
}

// SetSupportedTargets sets the "supported_targets" field.
func (u *BuilderUpsertOne) SetSupportedTargets(v []c2pb.Host_Platform) *BuilderUpsertOne {
	return u.Update(func(s *BuilderUpsert) {
		s.SetSupportedTargets(v)
	})
}

// UpdateSupportedTargets sets the "supported_targets" field to the value that was provided on create.
func (u *BuilderUpsertOne) UpdateSupportedTargets() *BuilderUpsertOne {
	return u.Update(func(s *BuilderUpsert) {
		s.UpdateSupportedTargets()
	})
}

// SetUpstream sets the "upstream" field.
func (u *BuilderUpsertOne) SetUpstream(v string) *BuilderUpsertOne {
	return u.Update(func(s *BuilderUpsert) {
		s.SetUpstream(v)
	})
}

// UpdateUpstream sets the "upstream" field to the value that was provided on create.
func (u *BuilderUpsertOne) UpdateUpstream() *BuilderUpsertOne {
	return u.Update(func(s *BuilderUpsert) {
		s.UpdateUpstream()
	})
}

// Exec executes the query.
func (u *BuilderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuilderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuilderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BuilderUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BuilderUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BuilderCreateBulk is the builder for creating many Builder entities in bulk.
type BuilderCreateBulk struct {
	config
	err      error
	builders []*BuilderCreate
	conflict []sql.ConflictOption
}

// Save creates the Builder entities in the database.
func (bcb *BuilderCreateBulk) Save(ctx context.Context) ([]*Builder, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Builder, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BuilderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = bcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BuilderCreateBulk) SaveX(ctx context.Context) []*Builder {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BuilderCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BuilderCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Builder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BuilderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bcb *BuilderCreateBulk) OnConflict(opts ...sql.ConflictOption) *BuilderUpsertBulk {
	bcb.conflict = opts
	return &BuilderUpsertBulk{
		create: bcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Builder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bcb *BuilderCreateBulk) OnConflictColumns(columns ...string) *BuilderUpsertBulk {
	bcb.conflict = append(bcb.conflict, sql.ConflictColumns(columns...))
	return &BuilderUpsertBulk{
		create: bcb,
	}
}

// BuilderUpsertBulk is the builder for "upsert"-ing
// a bulk of Builder nodes.
type BuilderUpsertBulk struct {
	create *BuilderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Builder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BuilderUpsertBulk) UpdateNewValues() *BuilderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(builder.FieldCreatedAt)
			}
			if _, exists := b.mutation.Identifier(); exists {
				s.SetIgnore(builder.FieldIdentifier)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Builder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BuilderUpsertBulk) Ignore() *BuilderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BuilderUpsertBulk) DoNothing() *BuilderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BuilderCreateBulk.OnConflict
// documentation for more info.
func (u *BuilderUpsertBulk) Update(set func(*BuilderUpsert)) *BuilderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BuilderUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastModifiedAt sets the "last_modified_at" field.
func (u *BuilderUpsertBulk) SetLastModifiedAt(v time.Time) *BuilderUpsertBulk {
	return u.Update(func(s *BuilderUpsert) {
		s.SetLastModifiedAt(v)
	})
}

// UpdateLastModifiedAt sets the "last_modified_at" field to the value that was provided on create.
func (u *BuilderUpsertBulk) UpdateLastModifiedAt() *BuilderUpsertBulk {
	return u.Update(func(s *BuilderUpsert) {
		s.UpdateLastModifiedAt()
	})
}

// SetSupportedTargets sets the "supported_targets" field.
func (u *BuilderUpsertBulk) SetSupportedTargets(v []c2pb.Host_Platform) *BuilderUpsertBulk {
	return u.Update(func(s *BuilderUpsert) {
		s.SetSupportedTargets(v)
	})
}

// UpdateSupportedTargets sets the "supported_targets" field to the value that was provided on create.
func (u *BuilderUpsertBulk) UpdateSupportedTargets() *BuilderUpsertBulk {
	return u.Update(func(s *BuilderUpsert) {
		s.UpdateSupportedTargets()
	})
}

// SetUpstream sets the "upstream" field.
func (u *BuilderUpsertBulk) SetUpstream(v string) *BuilderUpsertBulk {
	return u.Update(func(s *BuilderUpsert) {
		s.SetUpstream(v)
	})
}

// UpdateUpstream sets the "upstream" field to the value that was provided on create.
func (u *BuilderUpsertBulk) UpdateUpstream() *BuilderUpsertBulk {
	return u.Update(func(s *BuilderUpsert) {
		s.UpdateUpstream()
	})
}

// Exec executes the query.
func (u *BuilderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BuilderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BuilderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BuilderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
