// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"realm.pub/tavern/internal/ent/hostprocess"
	"realm.pub/tavern/internal/ent/predicate"
)

// HostProcessDelete is the builder for deleting a HostProcess entity.
type HostProcessDelete struct {
	config
	hooks    []Hook
	mutation *HostProcessMutation
}

// Where appends a list predicates to the HostProcessDelete builder.
func (hpd *HostProcessDelete) Where(ps ...predicate.HostProcess) *HostProcessDelete {
	hpd.mutation.Where(ps...)
	return hpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hpd *HostProcessDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hpd.sqlExec, hpd.mutation, hpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hpd *HostProcessDelete) ExecX(ctx context.Context) int {
	n, err := hpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hpd *HostProcessDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hostprocess.Table, sqlgraph.NewFieldSpec(hostprocess.FieldID, field.TypeInt))
	if ps := hpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hpd.mutation.done = true
	return affected, err
}

// HostProcessDeleteOne is the builder for deleting a single HostProcess entity.
type HostProcessDeleteOne struct {
	hpd *HostProcessDelete
}

// Where appends a list predicates to the HostProcessDelete builder.
func (hpdo *HostProcessDeleteOne) Where(ps ...predicate.HostProcess) *HostProcessDeleteOne {
	hpdo.hpd.mutation.Where(ps...)
	return hpdo
}

// Exec executes the deletion query.
func (hpdo *HostProcessDeleteOne) Exec(ctx context.Context) error {
	n, err := hpdo.hpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hostprocess.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hpdo *HostProcessDeleteOne) ExecX(ctx context.Context) {
	if err := hpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
