// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"realm.pub/tavern/internal/ent/scheduledtask"
	"realm.pub/tavern/internal/ent/tome"
)

// ScheduledTask is the model entity for the ScheduledTask schema.
type ScheduledTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Timestamp of when this ent was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp of when this ent was last updated
	LastModifiedAt time.Time `json:"last_modified_at,omitempty"`
	// Name of the scheduled task
	Name string `json:"name,omitempty"`
	// Information about the scheduled task
	Description string `json:"description,omitempty"`
	// If true, this tome will automatically be queued for all new Beacon callbacks.
	RunOnNewBeaconCallback bool `json:"run_on_new_beacon_callback,omitempty"`
	// If true, this tome will automatically be queued for the first new callback on a Host.
	RunOnFirstHostCallback bool `json:"run_on_first_host_callback,omitempty"`
	// Value of parameters that will be used when creating quests from this scheduled task (as a JSON string).
	Parameters string `json:"parameters,omitempty"`
	// Cron-like schedule for this tome to be automatically queued.
	RunOnSchedule string `json:"run_on_schedule,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduledTaskQuery when eager-loading is set.
	Edges               ScheduledTaskEdges `json:"edges"`
	scheduled_task_tome *int
	selectValues        sql.SelectValues
}

// ScheduledTaskEdges holds the relations/edges for other nodes in the graph.
type ScheduledTaskEdges struct {
	// The Tome that this ScheduledTask will run.
	Tome *Tome `json:"tome,omitempty"`
	// If a schedule is configured for this tome, you may limit which hosts it runs on using this field. If a schedule is configured but no hosts are set, the tome will run on all hosts.
	ScheduledHosts []*Host `json:"scheduled_hosts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedScheduledHosts map[string][]*Host
}

// TomeOrErr returns the Tome value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduledTaskEdges) TomeOrErr() (*Tome, error) {
	if e.Tome != nil {
		return e.Tome, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tome.Label}
	}
	return nil, &NotLoadedError{edge: "tome"}
}

// ScheduledHostsOrErr returns the ScheduledHosts value or an error if the edge
// was not loaded in eager-loading.
func (e ScheduledTaskEdges) ScheduledHostsOrErr() ([]*Host, error) {
	if e.loadedTypes[1] {
		return e.ScheduledHosts, nil
	}
	return nil, &NotLoadedError{edge: "scheduled_hosts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduledTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scheduledtask.FieldRunOnNewBeaconCallback, scheduledtask.FieldRunOnFirstHostCallback:
			values[i] = new(sql.NullBool)
		case scheduledtask.FieldID:
			values[i] = new(sql.NullInt64)
		case scheduledtask.FieldName, scheduledtask.FieldDescription, scheduledtask.FieldParameters, scheduledtask.FieldRunOnSchedule:
			values[i] = new(sql.NullString)
		case scheduledtask.FieldCreatedAt, scheduledtask.FieldLastModifiedAt:
			values[i] = new(sql.NullTime)
		case scheduledtask.ForeignKeys[0]: // scheduled_task_tome
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduledTask fields.
func (st *ScheduledTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scheduledtask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			st.ID = int(value.Int64)
		case scheduledtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				st.CreatedAt = value.Time
			}
		case scheduledtask.FieldLastModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_modified_at", values[i])
			} else if value.Valid {
				st.LastModifiedAt = value.Time
			}
		case scheduledtask.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				st.Name = value.String
			}
		case scheduledtask.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				st.Description = value.String
			}
		case scheduledtask.FieldRunOnNewBeaconCallback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field run_on_new_beacon_callback", values[i])
			} else if value.Valid {
				st.RunOnNewBeaconCallback = value.Bool
			}
		case scheduledtask.FieldRunOnFirstHostCallback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field run_on_first_host_callback", values[i])
			} else if value.Valid {
				st.RunOnFirstHostCallback = value.Bool
			}
		case scheduledtask.FieldParameters:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parameters", values[i])
			} else if value.Valid {
				st.Parameters = value.String
			}
		case scheduledtask.FieldRunOnSchedule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_on_schedule", values[i])
			} else if value.Valid {
				st.RunOnSchedule = value.String
			}
		case scheduledtask.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field scheduled_task_tome", value)
			} else if value.Valid {
				st.scheduled_task_tome = new(int)
				*st.scheduled_task_tome = int(value.Int64)
			}
		default:
			st.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduledTask.
// This includes values selected through modifiers, order, etc.
func (st *ScheduledTask) Value(name string) (ent.Value, error) {
	return st.selectValues.Get(name)
}

// QueryTome queries the "tome" edge of the ScheduledTask entity.
func (st *ScheduledTask) QueryTome() *TomeQuery {
	return NewScheduledTaskClient(st.config).QueryTome(st)
}

// QueryScheduledHosts queries the "scheduled_hosts" edge of the ScheduledTask entity.
func (st *ScheduledTask) QueryScheduledHosts() *HostQuery {
	return NewScheduledTaskClient(st.config).QueryScheduledHosts(st)
}

// Update returns a builder for updating this ScheduledTask.
// Note that you need to call ScheduledTask.Unwrap() before calling this method if this ScheduledTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (st *ScheduledTask) Update() *ScheduledTaskUpdateOne {
	return NewScheduledTaskClient(st.config).UpdateOne(st)
}

// Unwrap unwraps the ScheduledTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (st *ScheduledTask) Unwrap() *ScheduledTask {
	_tx, ok := st.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduledTask is not a transactional entity")
	}
	st.config.driver = _tx.drv
	return st
}

// String implements the fmt.Stringer.
func (st *ScheduledTask) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduledTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", st.ID))
	builder.WriteString("created_at=")
	builder.WriteString(st.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_modified_at=")
	builder.WriteString(st.LastModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(st.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(st.Description)
	builder.WriteString(", ")
	builder.WriteString("run_on_new_beacon_callback=")
	builder.WriteString(fmt.Sprintf("%v", st.RunOnNewBeaconCallback))
	builder.WriteString(", ")
	builder.WriteString("run_on_first_host_callback=")
	builder.WriteString(fmt.Sprintf("%v", st.RunOnFirstHostCallback))
	builder.WriteString(", ")
	builder.WriteString("parameters=")
	builder.WriteString(st.Parameters)
	builder.WriteString(", ")
	builder.WriteString("run_on_schedule=")
	builder.WriteString(st.RunOnSchedule)
	builder.WriteByte(')')
	return builder.String()
}

// NamedScheduledHosts returns the ScheduledHosts named value or an error if the edge was not
// loaded in eager-loading with this name.
func (st *ScheduledTask) NamedScheduledHosts(name string) ([]*Host, error) {
	if st.Edges.namedScheduledHosts == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := st.Edges.namedScheduledHosts[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (st *ScheduledTask) appendNamedScheduledHosts(name string, edges ...*Host) {
	if st.Edges.namedScheduledHosts == nil {
		st.Edges.namedScheduledHosts = make(map[string][]*Host)
	}
	if len(edges) == 0 {
		st.Edges.namedScheduledHosts[name] = []*Host{}
	} else {
		st.Edges.namedScheduledHosts[name] = append(st.Edges.namedScheduledHosts[name], edges...)
	}
}

// ScheduledTasks is a parsable slice of ScheduledTask.
type ScheduledTasks []*ScheduledTask
