// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"realm.pub/tavern/internal/ent/asset"
	"realm.pub/tavern/internal/ent/host"
	"realm.pub/tavern/internal/ent/predicate"
	"realm.pub/tavern/internal/ent/repository"
	"realm.pub/tavern/internal/ent/tome"
	"realm.pub/tavern/internal/ent/user"
)

// TomeQuery is the builder for querying Tome entities.
type TomeQuery struct {
	config
	ctx                     *QueryContext
	order                   []tome.OrderOption
	inters                  []Interceptor
	predicates              []predicate.Tome
	withAssets              *AssetQuery
	withUploader            *UserQuery
	withRepository          *RepositoryQuery
	withScheduledHosts      *HostQuery
	withFKs                 bool
	modifiers               []func(*sql.Selector)
	loadTotal               []func(context.Context, []*Tome) error
	withNamedAssets         map[string]*AssetQuery
	withNamedScheduledHosts map[string]*HostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TomeQuery builder.
func (tq *TomeQuery) Where(ps ...predicate.Tome) *TomeQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TomeQuery) Limit(limit int) *TomeQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TomeQuery) Offset(offset int) *TomeQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TomeQuery) Unique(unique bool) *TomeQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TomeQuery) Order(o ...tome.OrderOption) *TomeQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryAssets chains the current query on the "assets" edge.
func (tq *TomeQuery) QueryAssets() *AssetQuery {
	query := (&AssetClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tome.Table, tome.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, tome.AssetsTable, tome.AssetsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUploader chains the current query on the "uploader" edge.
func (tq *TomeQuery) QueryUploader() *UserQuery {
	query := (&UserClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tome.Table, tome.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tome.UploaderTable, tome.UploaderColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRepository chains the current query on the "repository" edge.
func (tq *TomeQuery) QueryRepository() *RepositoryQuery {
	query := (&RepositoryClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tome.Table, tome.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tome.RepositoryTable, tome.RepositoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScheduledHosts chains the current query on the "scheduled_hosts" edge.
func (tq *TomeQuery) QueryScheduledHosts() *HostQuery {
	query := (&HostClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tome.Table, tome.FieldID, selector),
			sqlgraph.To(host.Table, host.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tome.ScheduledHostsTable, tome.ScheduledHostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tome entity from the query.
// Returns a *NotFoundError when no Tome was found.
func (tq *TomeQuery) First(ctx context.Context) (*Tome, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tome.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TomeQuery) FirstX(ctx context.Context) *Tome {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tome ID from the query.
// Returns a *NotFoundError when no Tome ID was found.
func (tq *TomeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tome.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TomeQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tome entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tome entity is found.
// Returns a *NotFoundError when no Tome entities are found.
func (tq *TomeQuery) Only(ctx context.Context) (*Tome, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tome.Label}
	default:
		return nil, &NotSingularError{tome.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TomeQuery) OnlyX(ctx context.Context) *Tome {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tome ID in the query.
// Returns a *NotSingularError when more than one Tome ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TomeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tome.Label}
	default:
		err = &NotSingularError{tome.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TomeQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Tomes.
func (tq *TomeQuery) All(ctx context.Context) ([]*Tome, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryAll)
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tome, *TomeQuery]()
	return withInterceptors[[]*Tome](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TomeQuery) AllX(ctx context.Context) []*Tome {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tome IDs.
func (tq *TomeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryIDs)
	if err = tq.Select(tome.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TomeQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TomeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryCount)
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TomeQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TomeQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TomeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryExist)
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TomeQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TomeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TomeQuery) Clone() *TomeQuery {
	if tq == nil {
		return nil
	}
	return &TomeQuery{
		config:             tq.config,
		ctx:                tq.ctx.Clone(),
		order:              append([]tome.OrderOption{}, tq.order...),
		inters:             append([]Interceptor{}, tq.inters...),
		predicates:         append([]predicate.Tome{}, tq.predicates...),
		withAssets:         tq.withAssets.Clone(),
		withUploader:       tq.withUploader.Clone(),
		withRepository:     tq.withRepository.Clone(),
		withScheduledHosts: tq.withScheduledHosts.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithAssets tells the query-builder to eager-load the nodes that are connected to
// the "assets" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TomeQuery) WithAssets(opts ...func(*AssetQuery)) *TomeQuery {
	query := (&AssetClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withAssets = query
	return tq
}

// WithUploader tells the query-builder to eager-load the nodes that are connected to
// the "uploader" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TomeQuery) WithUploader(opts ...func(*UserQuery)) *TomeQuery {
	query := (&UserClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withUploader = query
	return tq
}

// WithRepository tells the query-builder to eager-load the nodes that are connected to
// the "repository" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TomeQuery) WithRepository(opts ...func(*RepositoryQuery)) *TomeQuery {
	query := (&RepositoryClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withRepository = query
	return tq
}

// WithScheduledHosts tells the query-builder to eager-load the nodes that are connected to
// the "scheduled_hosts" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TomeQuery) WithScheduledHosts(opts ...func(*HostQuery)) *TomeQuery {
	query := (&HostClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withScheduledHosts = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tome.Query().
//		GroupBy(tome.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TomeQuery) GroupBy(field string, fields ...string) *TomeGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TomeGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = tome.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Tome.Query().
//		Select(tome.FieldCreatedAt).
//		Scan(ctx, &v)
func (tq *TomeQuery) Select(fields ...string) *TomeSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TomeSelect{TomeQuery: tq}
	sbuild.label = tome.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TomeSelect configured with the given aggregations.
func (tq *TomeQuery) Aggregate(fns ...AggregateFunc) *TomeSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TomeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !tome.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TomeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tome, error) {
	var (
		nodes       = []*Tome{}
		withFKs     = tq.withFKs
		_spec       = tq.querySpec()
		loadedTypes = [4]bool{
			tq.withAssets != nil,
			tq.withUploader != nil,
			tq.withRepository != nil,
			tq.withScheduledHosts != nil,
		}
	)
	if tq.withUploader != nil || tq.withRepository != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tome.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tome).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tome{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withAssets; query != nil {
		if err := tq.loadAssets(ctx, query, nodes,
			func(n *Tome) { n.Edges.Assets = []*Asset{} },
			func(n *Tome, e *Asset) { n.Edges.Assets = append(n.Edges.Assets, e) }); err != nil {
			return nil, err
		}
	}
	if query := tq.withUploader; query != nil {
		if err := tq.loadUploader(ctx, query, nodes, nil,
			func(n *Tome, e *User) { n.Edges.Uploader = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withRepository; query != nil {
		if err := tq.loadRepository(ctx, query, nodes, nil,
			func(n *Tome, e *Repository) { n.Edges.Repository = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withScheduledHosts; query != nil {
		if err := tq.loadScheduledHosts(ctx, query, nodes,
			func(n *Tome) { n.Edges.ScheduledHosts = []*Host{} },
			func(n *Tome, e *Host) { n.Edges.ScheduledHosts = append(n.Edges.ScheduledHosts, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range tq.withNamedAssets {
		if err := tq.loadAssets(ctx, query, nodes,
			func(n *Tome) { n.appendNamedAssets(name) },
			func(n *Tome, e *Asset) { n.appendNamedAssets(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range tq.withNamedScheduledHosts {
		if err := tq.loadScheduledHosts(ctx, query, nodes,
			func(n *Tome) { n.appendNamedScheduledHosts(name) },
			func(n *Tome, e *Host) { n.appendNamedScheduledHosts(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range tq.loadTotal {
		if err := tq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TomeQuery) loadAssets(ctx context.Context, query *AssetQuery, nodes []*Tome, init func(*Tome), assign func(*Tome, *Asset)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Tome)
	nids := make(map[int]map[*Tome]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(tome.AssetsTable)
		s.Join(joinT).On(s.C(asset.FieldID), joinT.C(tome.AssetsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(tome.AssetsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(tome.AssetsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Tome]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Asset](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "assets" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (tq *TomeQuery) loadUploader(ctx context.Context, query *UserQuery, nodes []*Tome, init func(*Tome), assign func(*Tome, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Tome)
	for i := range nodes {
		if nodes[i].tome_uploader == nil {
			continue
		}
		fk := *nodes[i].tome_uploader
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tome_uploader" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *TomeQuery) loadRepository(ctx context.Context, query *RepositoryQuery, nodes []*Tome, init func(*Tome), assign func(*Tome, *Repository)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Tome)
	for i := range nodes {
		if nodes[i].tome_repository == nil {
			continue
		}
		fk := *nodes[i].tome_repository
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repository.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tome_repository" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *TomeQuery) loadScheduledHosts(ctx context.Context, query *HostQuery, nodes []*Tome, init func(*Tome), assign func(*Tome, *Host)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tome)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Host(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tome.ScheduledHostsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tome_scheduled_hosts
		if fk == nil {
			return fmt.Errorf(`foreign-key "tome_scheduled_hosts" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tome_scheduled_hosts" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tq *TomeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TomeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tome.Table, tome.Columns, sqlgraph.NewFieldSpec(tome.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tome.FieldID)
		for i := range fields {
			if fields[i] != tome.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TomeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(tome.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = tome.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedAssets tells the query-builder to eager-load the nodes that are connected to the "assets"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (tq *TomeQuery) WithNamedAssets(name string, opts ...func(*AssetQuery)) *TomeQuery {
	query := (&AssetClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if tq.withNamedAssets == nil {
		tq.withNamedAssets = make(map[string]*AssetQuery)
	}
	tq.withNamedAssets[name] = query
	return tq
}

// WithNamedScheduledHosts tells the query-builder to eager-load the nodes that are connected to the "scheduled_hosts"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (tq *TomeQuery) WithNamedScheduledHosts(name string, opts ...func(*HostQuery)) *TomeQuery {
	query := (&HostClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if tq.withNamedScheduledHosts == nil {
		tq.withNamedScheduledHosts = make(map[string]*HostQuery)
	}
	tq.withNamedScheduledHosts[name] = query
	return tq
}

// TomeGroupBy is the group-by builder for Tome entities.
type TomeGroupBy struct {
	selector
	build *TomeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TomeGroupBy) Aggregate(fns ...AggregateFunc) *TomeGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TomeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, ent.OpQueryGroupBy)
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TomeQuery, *TomeGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TomeGroupBy) sqlScan(ctx context.Context, root *TomeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TomeSelect is the builder for selecting fields of Tome entities.
type TomeSelect struct {
	*TomeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TomeSelect) Aggregate(fns ...AggregateFunc) *TomeSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TomeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, ent.OpQuerySelect)
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TomeQuery, *TomeSelect](ctx, ts.TomeQuery, ts, ts.inters, v)
}

func (ts *TomeSelect) sqlScan(ctx context.Context, root *TomeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
