name: Tavern Tests

on:
  workflow_dispatch: ~
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - tavern/**

env:
  CARGO_TERM_COLOR: always

jobs:
  tavern:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ⚡ Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
    - name: 🔨 Build
      run: go build -v -o ./build/tavern ./tavern
    - name: 🔎 Test
      run: go test -v -race -coverprofile='coverage.out' -covermode=atomic ./tavern/...
    - name: 📶 Upload Coverage Results
      uses: codecov/codecov-action@v3
